apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: database-services
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  homelab.io/role: database
          - git:
              repoURL: https://github.com/IamVanshKhanna/homelab-prod.git
              revision: HEAD
              directories:
                - path: config/argocd/services/database/*
  template:
    metadata:
      name: 'database-{{path.basename}}-{{name}}'
    spec:
      project: homelab
      source:
        repoURL: https://github.com/IamVanshKhanna/homelab-prod.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: '{{server}}'
        namespace: databases
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PruneLast=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m