apiVersion: v1
kind: Secret
metadata:
  name: thanos-objstore-config
  namespace: monitoring
type: Opaque
stringData:
  objstore.yml: |
    type: S3
    config:
      bucket: homelab-thanos
      endpoint: s3.us-east-005.backblazeb2.com
      access_key: ${B2_KEY_ID}
      secret_key: ${B2_APP_KEY}
      insecure: false
      signature_version2: false
      part_size: 134217728
      sse_type: ""
      sse_kms_key_id: ""
      sse_kms_encryption_context: ""
      http_config:
        idle_conn_timeout: 90s
        response_header_timeout: 2m
        insecure_skip_verify: false