# Thanos Sidecar values for workload clusters

prometheus:
  url: http://prometheus.monitoring:9090

objstore:
  config:
    type: S3
    config:
      bucket: homelab-thanos
      endpoint: s3.us-east-005.backblazeb2.com
      access_key: ${B2_KEY_ID}
      secret_key: ${B2_APP_KEY}

httpAddress: 0.0.0.0:10902
grpcAddress: 0.0.0.0:10901

reloader:
  configFile: /etc/prometheus/prometheus.yml
  ruleDir: /etc/prometheus/rules

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi