apiVersion: submariner.io/v1alpha1
kind: Submariner
metadata:
  name: submariner
  namespace: submariner-operator
spec:
  brokerK8sSecret: submariner-broker
  credentialsSecret: submariner-credentials
  cni: "calico"
  natEnabled: true
  globalnetEnabled: true
  serviceDiscoveryEnabled: true
  clusterid: homelab-pi5
  clusterCidr: 192.168.0.0/16
  serviceCidr: 10.96.0.0/12
  globalCidr: 242.0.0.0/8
  globalnet:
    enabled: true
    clusterSize: 256
  connectionTimeout: 30s
  reconnectTimeout: 10s
  debug: false