apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: node-drain-engine
  namespace: litmus
spec:
  appinfo:
    appns: "kube-system"
    applabel: "kubernetes.io/hostname=node-2"
  chaosServiceAccount: litmus-admin
  experiments:
    - name: node-drain
      spec:
        components:
          env:
            - name: TOTAL_CHAOS_DURATION
              value: "120"
            - name: CHAOS_INTERVAL
              value: "30"
            - name: NODE_LABEL
              value: "kubernetes.io/hostname"
            - name: TARGET_NODE
              value: "node-2"
            - name: FORCE
              value: "true"
            - name: EVICION_TIMEOUT
              value: "60"