apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: pod-network-latency-engine
  namespace: litmus
spec:
  appinfo:
    appns: "apps"
    applabel: "app.kubernetes.io/name=nextcloud"
  chaosServiceAccount: litmus-admin
  experiments:
    - name: pod-network-latency
      spec:
        components:
          env:
            - name: TOTAL_CHAOS_DURATION
              value: "60"
            - name: CHAOS_INTERVAL
              value: "10"
            - name: NETWORK_LATENCY
              value: "1000"
            - name: NETWORK_LATENCY_UNIT
              value: "ms"
            - name: JITTER
              value: "100"
            - name: TARGET_PODS
              value: ""
            - name: PODS_AFFECTED_PERC
              value: "50"