apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: pod-network-loss-engine
  namespace: litmus
spec:
  appinfo:
    appns: "apps"
    applabel: "app.kubernetes.io/name=nextcloud"
  chaosServiceAccount: litmus-admin
  experiments:
    - name: pod-network-loss
      spec:
        components:
          env:
            - name: TOTAL_CHAOS_DURATION
              value: "60"
            - name: CHAOS_INTERVAL
              value: "10"
            - name: NETWORK_LOSS_PERCENTAGE
              value: "50"
            - name: NETWORK_LOSS_CORRELATION
              value: "50"
            - name: TARGET_PODS
              value: ""
            - name: PODS_AFFECTED_PERC
              value: "50"