apiVersion: controlplane.cluster.x-k8s.io/v1
kind: KubeadmControlPlane
metadata:
  name: homelab-pi4-cp
  namespace: homelab-clusters
spec:
  replicas: 1
  version: v1.28.5
  machineTemplate:
    infrastructureRef:
      kind: DockerMachineTemplate
      apiVersion: infrastructure.cluster.x-k8s.io/v1
      name: homelab-pi4-cp
  kubeadmConfigSpec:
    clusterConfiguration:
      controllerManager:
        extraArgs:
          node-cidr-mask-size: "24"
      apiServer:
        extraArgs:
          default-not-ready-toleration-seconds: "30"
          default-unreachable-toleration-seconds: "30"
    initConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          max-pods: "110"
          eviction-hard: "memory.available<500Mi,nodefs.available<10%"
    joinConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          max-pods: "110"
          eviction-hard: "memory.available<500Mi,nodefs.available<10%"