apiVersion: v1
kind: ResourceQuota
metadata:
  name: security-quota
  namespace: security
spec:
  hard:
    requests.cpu: "500m"
    requests.memory: 1Gi
    limits.cpu: "1"
    limits.memory: 2Gi
    requests.storage: "20Gi"
    persistentvolumeclaims: "5"
    pods: "20"
    services: "10"
    secrets: "10"
    configmaps: "10"
