apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: homelab
  source:
    repoURL: https://charts.jetstack.io
    targetRevision: "1.13.0"
    chart: jetstack/cert-manager
    helm:
      valueFiles:
      - ../../helmfile/values/defaults.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m