apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ollama-cluster
  namespace: argocd
spec:
  project: homelab
  source:
    repoURL: https://github.com/IamVanshKhanna/homelab-prod.git
    targetRevision: main
    path: stacks/ollama-cluster/k8s
    helm:
      valueFiles:
      - ../../../stacks/ollama-cluster/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: ai
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m