apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: policy-exceptions
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: exclude-system-namespaces
      match:
        any:
        - resources:
            kinds:
              - Pod
          namespaces:
            - kube-system
            - kube-public
            - kube-node-lease
            - kyverno
            - argocd
            - cert-manager
            - monitoring
            - logging
            - tracing
            - traefik
            - auth
            - secrets
            - longhorn-system
            - external-dns
            - postgres-system
            - argocd