apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restrict-external-secrets
  labels:
    app.kubernetes.io/name: kyverno
    policy-type: operational
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: validate-external-secret
      match:
        any:
          - resources:
              kinds:
                - ExternalSecret
      validate:
        message: "ExternalSecret must reference valid ClusterSecretStore and have valid data"
        pattern:
          spec:
            secretStoreRef:
              kind: ClusterSecretStore
              name: "*"
            data:
              - secretKey: "*"
                remoteRef:
                  key: "*"