apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authelia-db-postgres
  namespace: argocd
spec:
  project: homelab
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: "15.5.0"
    chart: bitnami/postgresql
    helm:
      valueFiles:
      - ../../helmfile/values/defaults.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: auth
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m