apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflare-credentials-external-dns
  namespace: argocd
spec:
  project: homelab
  source:
    repoURL: ""
    targetRevision: ""
    chart: ""
    helm:
      valueFiles: []
  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true