apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: security-allow-egress
  namespace: security
  labels:
    app.kubernetes.io/name: crowdsec
    policy-type: allow
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: crowdsec
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: databases
      ports:
        - protocol: TCP
          port: 5432
    - to: []  # Allow external egress to CrowdSec Central API
      ports:
        - protocol: TCP
          port: 443