apiVersion: batch/v1
kind: CronJob
metadata:
  name: spot-batch-jobs
  namespace: ops
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          nodeSelector:
            lifecycle: spot
          tolerations:
          - key: "dedicated"
            operator: "Equal"
            value: "spot"
            effect: "NoSchedule"
          restartPolicy: OnFailure
