apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cluster.yaml
  - controlplane.yaml
  - metal3cluster.yaml
  - metal3-machine-template-cp.yaml
  - machinedeployment.yaml
  - metal3-machine-template-md.yaml
  - kubeadmconfig-template.yaml
namespace: homelab-clusters
commonLabels:
  homelab.io/managed-by: cluster-api
  homelab.io/cluster: homelab-pi5