apiVersion: cluster.x-k8s.io/v1
kind: MachineDeployment
metadata:
  name: homelab-pi5-md-0
  namespace: homelab-clusters
spec:
  clusterName: homelab-pi5
  replicas: 3
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: homelab-pi5
  template:
    spec:
      clusterName: homelab-pi5
      version: v1.28.5
      bootstrap:
        configRef:
          kind: KubeadmConfigTemplate
          apiVersion: bootstrap.cluster.x-k8s.io/v1
          name: homelab-pi5-md-0
      infrastructureRef:
        kind: Metal3MachineTemplate
        apiVersion: infrastructure.cluster.x-k8s.io/v1
        name: homelab-pi5-md-0