apiVersion: v1
kind: ResourceQuota
metadata:
  name: ai-quota
  namespace: ai
spec:
  hard:
    requests.cpu: "250m"
    requests.memory: 512Mi
    limits.cpu: "500m"
    limits.memory: 1Gi
    requests.storage: "10Gi"
    persistentvolumeclaims: "3"
    pods: "10"
    services: "5"
    secrets: "5"
    configmaps: "10"
